#define EVENT_TYPE_ACCEPT 0
#define EVENT_TYPE_SERVER_READ 200
#define EVENT_TYPE_SERVER_WRITE_COMPLETE 201
#define EVENT_TYPE_SERVER_WRITE_PARTIAL 202
#define EVENT_TYPE_SERVER_CLOSE 203
#define EVENT_TYPE_SERVER_WRITE_HEADER 204
#define EVENT_TYPE_HTTP_FETCH 300
#define EVENT_TYPE_HTTP_FETCH_IPV4 301
#define EVENT_TYPE_HTTP_READ_HEADER 302
#define EVENT_TYPE_HTTP_READ_CONTENT 303
#define EVENT_TYPE_DNS_VERIFY 400
#define EVENT_TYPE_DNS_FETCHAAAA 401
#define EVENT_TYPE_CACHE_EXISTS 500
#define EVENT_TYPE_CACHE_READ_HEADER 501
#define EVENT_TYPE_CACHE_READ_CONTENT 502
#define EVENT_TYPE_CACHE_VERIFY_INVALID 503
#define EVENT_TYPE_CACHE_WRITE_HEADER 504
#define EVENT_TYPE_CACHE_WRITE_CONTENT 505
#define EVENT_TYPE_CACHE_CLOSE 506
#define EVENT_TYPE_CACHE_COPY_CONTENT 507
#define EVENT_TYPE_STREAM_NEXT 600

#define RESOURCE_TYPE_UNDEFINED 0
#define RESOURCE_TYPE_STREAMING 1
#define RESOURCE_TYPE_CACHE 2

#define TRANSFER_MODE_HEADER_SOON_AS_POSSIBLE 0
#define TRANSFER_MODE_WAIT_UNTIL_COMPLETE 1

#define EMPTY_BUFFER 12345678
#define END_BUFFER 12345679

#define SOCKET_CLOSED -32
